version: '3.1'

services:

  portainer:
    image: portainer/portainer:1.15.2
    networks:
      - ntw_front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          cpus: '0.33'
          memory: 20M
        reservations:
          cpus: '0.05'
          memory: 10M
      labels:
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=PathPrefixStrip:/portainer"
        - "traefik.port=9000"
        - "traefik.enable=true"
        - "traefik.frontend.entryPoints=http"
        - "traefik.docker.network=ntw_front"
        - "traefik.weight=10"
        - "traefik.frontend.passHostHeader=true"

networks:
  ntw_front:
    external: true

# potential setup https://github.com/portainer/portainer/issues/461

# Inspired from https://github.com/portainer/portainer-compose/blob/master/docker-stack.yml
# by Pascal Andy | # https://twitter.com/askpascalandy
# https://github.com/pascalandy/docker-stack-this
#